meta_product_name: "swiss massiv"
meta_title: "swiss massiv - handmade skis"
meta_description: "swiss massiv skis are handmade in the heart of Switzerland. Each ski is one of a kind and has a highly complex design."
meta_image: "meta.jpg"
twitter_account: "@swissmassiv"
